### ISSUE TITLE
C++ icon isn't shown

### ISSUE THREAD

**Issue by NachtgeistW** [hritik5102/hritik5102#1]
Use **%2B** to inplace **+** in `![C++](https://img.shields.io/badge/-C++-00599C?style=flat&logo=c++&link=https://github.com/hritik5102)` can solve this.

![C++](https://img.shields.io/badge/-C++-00599C?style=flat&logo=c%2B%2B&link=https://github.com/hritik5102)

Sorry to interrupt you. I was writing my README.md and loved yours design very much, so I decided to learn yours badge design, but C++ icon wasn't shown correctly, which made me very frustrated. Therefore, I try to fix it. Thank you for sharing your excellent README.md. And Sorry for my poor English if this issue confuse you.

**Comment by hritik5102** [comment]
@NachtgeistW Thanks for informing 👍 , I'll fix that bug and by the way your English is too good probably better than me :)
