### ISSUE TITLE
Join the org

### ISSUE THREAD

**Issue by VasudevJaiswal** [hritik5102/hritik5102#3]
[CLICK HERE](https://github.com/Jaidevstudio/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization)

**Comment by hritik5102** [comment]
@VasudevJaiswal Done

**Comment by VasudevJaiswal** [comment]
Thank you for contribution 🙂
